config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :game, only: %i[new create update]
  root "games#new"
  get "*path", to: redirect("/")
end

app/models/game.rb
# frozen_string_literal: true

class Game
  include ActiveModel::Model
  include ActiveModel::Serialization

  attr_accessor :player, :player_turn, :board, :moves, :computer, :winner

  validates_presence_of :player, :player_turn

  def initialize(attributes = {})
    @player = attributes[:player]
    @player_turn = attributes[:player_turn]
    @computer = Constants::PLAYER_DETAILS[@player]&.[](:opponent)
    @board = Array.new(Constants::BOARD_SIZE)
    @moves = {}
    @winner = nil
  end

  def make_player_move(position)
    if @winner || draw?
      @moves = {}
    else
      @board[position.to_i] = @player
      @moves[:player] = {
        character: @player,
        cell_id: "cell_#{position}"
      }
      @winner = @player if wins?(@player)
    end
  end

  def make_computer_move
    if @winner || draw?
      @moves = {}
    else
      position = ComputerMoveService.new(self, @computer).process
      @board[position] = @computer
      moves[:computer] = {
        character: @computer,
        cell_id: "cell_#{position}"
      }
      @winner = @computer if wins?(@computer)
    end
  end

  def draw?
    @board.compact.size == Constants::BOARD_SIZE
  end

  def wins?(character)
    [
      # horizontal wins
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],

      # vertical wins
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],

      # diagonal wins
      [0, 4, 8],
      [6, 4, 2]
    ].any? do |positions|
      @board[positions[0]] == character &&
      @board[positions[0]] == @board[positions[1]] &&
      @board[positions[1]] == @board[positions[2]]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :reset_session, only: :new
  before_action :load_game_data, only: :update
  after_action :store_game_data, only: %i[create update]

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    unless @game.valid?
      render status: :unprocessable_entity, json: { error: @game.errors.full_messages.to_sentence }
    end
    @game.make_computer_move if game_params[:player_turn] == Constants::SECOND_TURN
  end

  def update
    @game.make_player_move(game_params[:position])
    @game.make_computer_move
  end

  private

    def game_params
      params.require(:game).permit(:player, :player_turn, :position)
    end

    def store_game_data
      session[:game] = Marshal.dump(@game)
    end

    def load_game_data
      @game = Marshal.load(session[:game])
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/games/_board.html.erb
<div class="grid grid-cols-3 bg-black gap-0.5 border-2 border-black mx-auto" id="board">
  <% Constants::BOARD_SIZE.times do |position| %>
    <div class="flex justify-center items-center">
      <%= button_to game.board[position] || "", { action: "update" }, { id: "cell_#{position}", method: :patch, data: { turbo_stream: "true" }, params: { game: { position: position } }, class: "w-20 h-20", form_class: "w-20 h-20 bg-white text-4xl", disabled: disabled } %>
    </div>
  <% end %>
</div>

app/views/games/create.html.erb
<%= render partial: "board", locals: { game: @game, disabled: false } %>

app/views/games/new.html.erb
<div class="p-4 rounded-md shadow-md border w-1/3 mx-auto">
    <%= form_for @game, url: game_path do |form| %>
      <%= form.label :player_turn, t("form.player_turn"), class: "block text-sm text-gray-700 font-medium" %>
      <%= form.select :player_turn, [[t("form.first_turn"), Constants::FIRST_TURN], [t("form.second_turn"), Constants::SECOND_TURN]], {}, { class: "block mb-8 rounded-md shadow-sm w-full" } %>
      <%= form.label :player, t("form.player"), class: "block text-sm text-gray-700 font-medium" %>
      <%= form.select :player, [Constants::X, Constants::O], {}, { class: "block mb-8 rounded-md shadow-sm w-full" } %>
      <%= form.submit t("form.play"), class: "border bg-indigo-600 rounded-md shadow-sm text-white py-2 px-4 w-20", data: { turbo: "false" }%>
      <%= form.submit t("form.reset"), :type => "reset", class: "border rounded-md shadow-sm py-2 px-4 w-20" %>
    <% end %>
</div>

app/views/games/update.turbo_stream.erb
<% if @game.moves[:player] %>
  <turbo-stream action="replace" target=<%= @game.moves[:player][:cell_id] %> >
    <template>
        <button id=<%= @game.moves[:player][:cell_id] %> class="w-20 h-20" disabled="true">
          <%= @game.player %>
        </button>
    </template>
  </turbo-stream>
<% end %>

<% if @game.moves[:computer] %>
  <turbo-stream action="replace" target=<%= @game.moves[:computer][:cell_id] %> %>
    <template>
        <button id=<%= @game.moves[:computer][:cell_id] %> class="w-20 h-20" disabled="true">
          <%= @game.computer %>
        </button>
    </template>
  </turbo-stream>
<% end %>

<% if @game.winner || @game.draw? %>
  <turbo-stream action="replace" target="board">
    <template>
      <%= render partial: "board", locals: { game: @game, disabled: true } %>
    </template>
  </turbo-stream>

  <turbo-stream action="after" target="board">
    <template>
      <div class="text-2xl pt-6">
        <%= @game.winner ? t("wins", entity: @game.winner) : t("draw") %>
        <%= link_to t("try_again"), root_path, class: "underline" %>
      </div>
    </template>
  </turbo-stream>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("tic_tac_toe") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex justify-center items-center h-20 bg-indigo-700">
      <%= link_to t("tic_tac_toe"), root_path, class: "text-white text-3xl" %>
    </div>
    <main class="container mx-auto mt-28 px-5 flex flex-col justify-center items-center">
      <%= yield %>
    </main>
  </body>
</html>